const locale = {
    //English
    "en": {
        //1
        "page_1_title": "Creative Director<br/>Producer<br/>Music Composition<br/>Graphic Design",
        "page_1_name": "ลำธาร หาญตระกูล",
        "page_1_subname": "Lamtharn Hantrakul",
        "page_1_1_title": "Composer<br/>Creative Technologist<br/>Music AI Research Scientist",
        "page_1_1_story": "The Yaboi Hanoi project weaves music,<br/> design and technology into transcultural <br/>experiences. Lamtharn has developed <br/>intercultural audio AI tools at Google and <br/>Tiktok and has won international design <br/>awards for his cross-cultural musical <br/>instruments. He holds degrees with <br/>Distinction in Music Composition and Physics <br/>from Yale University and an M.S from Georgia <br/>Tech. He was born, raised and is currently <br/>based in Bangkok, Thailand.",
        "page_1_1_link": "www.yaboihanoi.com | Instagram @yaboihanoi | TikTok @yaboihanoi",
        //2
        "page_2_title": "Lyrics<br/>Vocals<br/>Original Track",
        "page_2_name": "ดอรช์ ดีนซ์",
        "page_2_subname": "Dorsh Deans",
        "page_2_1_title": "Singer Songwriter<br/>Music Producer",
        "page_2_1_story": "Dorsh is a Jamaican-American artist who <br/>recently released his second studio album <br/>entitled, ‘UI | UX’.  He has amassed over 6+ <br/>million streams on Spotify/Apple Music and his <br/>songs have been featured in a Netflix film and <br/>South Korean TV. <br/><br/> Throughout his career in both music and tech, <br/>Dorsh has worked with Celebrities, <br/>World-renowned Athletes, Global Brands and <br/>Fortune 500 Companies.",
        "page_2_1_link": "https://dorshmusic.com | https://ffm.to/ui-ux",
        //3
        "page_3_title": "Choreography<br/>Costume Design<br/>Dancer",
        "page_3_name": "ยุทธนา อัครเดชานัฏ",
        "page_3_subname": "Yuthana Agradechanat",
        "page_3_1_title": "Founding Director of the <br/>Kid Buak Sipp Dance Troupe <br/><br/>Head of Dance in the Department <br/>of Humanities and Social Science <br/>at Rajhabat University",
        "page_3_1_story": "Yuthana brings a wealth of experience in the <br/>performance, choreography and costume <br/>design of both classical forms of Thai Dance <br/>such as Khon (โขน) and modern dance styles. <br/>His works exploring new forms of Thai Dance <br/>are rooted in tradition and have been featured <br/>on the international stage in a variety of mediums.",
        "page_3_1_link": "https://web.facebook.com/profile.php?id=100050392154157",
        //4
        "page_4_title": "Choreography<br/>Costume Design<br/>Dancer",
        "page_4_name": "วีระพงษ์ ดรละคร",
        "page_4_subname": "Weerapong Donlakhon",
        "page_4_1_title": "Assistant Director of the <br/>Kid Buak Sipp Dance Troupe <br/><br/>Independant Artist",
        "page_4_1_story": "Weerapong is well-versed in the <br/>performance and choreography of both <br/>Classical Thai dance and contemporary <br/>dance. His works connect movements <br/>and traditions rooted in Thai culture with <br/>audiences on the international stage. ",
        "page_4_1_link": "https://web.facebook.com/profile.php?id=100050392154157",
        //5
        "page_5_title": "Dancer",
        "page_5_name": "สสิธร เพิ่มสิน",
        "page_5_subname": "Sasitorn Permsin",
        "page_5_1_title": "Kid Buak Sipp Member <br/><br/> Artist in the Department of Fine Arts,<br/> Ministry of Culture",
        "page_5_1_story": "Sasitorn is experienced in the <br/>performance Thai Classical Dance <br/>and specializes in the area of cultural <br/>preservation. She also explores new <br/>forms of dance based on these roots. <br/>Her works have been featured on <br/>both local and international stages.",
        "page_5_1_link": "https://web.facebook.com/profile.php?id=100050392154157",
        //6
        "page_6_title": "Dancer",
        "page_6_name": "รสสุคนธ์ เทียนจันทร์",
        "page_6_subname": "Rossukhon Tianchan",
        "page_6_1_title": "Kid Buak Sipp Member",
        "page_6_1_story": "Rossukhon is trained in both Classical <br/>Thai and Contemporary Dance. <br/>She has been featured in a variety of <br/>projects and performances within <br/>Thailand and internationally",
        "page_6_1_link": "https://web.facebook.com/profile.php?id=100050392154157",
        //7
        "page_7_title": "Cinematography<br/>Video editing<br/>Photography",
        "page_7_name": "ชัพวิชญ์ โพธิกุล",
        "page_7_subname": "Chappavit Potigul",
        "page_7_1_title": "Founding Director of Gaorilla <br/>Filmmaker",
        "page_7_1_story": "Chappavit is a director, producer and <br/>cinematographer who has been in the <br/>video industry since 2013. He has <br/>worked with clients including artists <br/>and brands both local and <br/>international, to produce <br/>advertisements, music videos and <br/>documentaries in a variety of <br/>different styles. ",
        "page_7_1_link": "https://www.instagram.com/imfilmmaker",
        //8 Dual Color Page
        "page_8_1_title": "Makeup Artist",
        "page_8_1_name": "ธัชชัย อนุมาศ",
        "page_8_1_subname": "Thatchai Anumas",
        "page_8_2_title": "Costume Fabrication Aide",
        "page_8_2_name": "ณัฐพงศ์ หาราศรี",
        "page_8_2_subname": "Natthaphong Harasri",
        "page_8_3_title": "Thai-to-English <br/Translation/Transcreation",
        "page_8_3_name": "สุกัญญา หาญตระกูล",
        "page_8_3_subname": "Sukanya Hantrakul",
        "page_8_4_title": "English-to-Mandarin <br/>Translation/Transcreation",
        "page_8_4_name": "孔卓悦",
        "page_8_4_subname": "Kong Zhuoyue",
        //9 Dual Color Page
        "page_9_1_title": "Website",
        "page_9_1_name": "ธฤต นาควัชระ",
        "page_9_1_subname": "Tarit Nakavajara",
        "page_9_2_title": "",
        "page_9_2_name": "",
        "page_9_2_subname": "",
        "page_9_3_title": "Project Funding",
        "page_9_3_name": "ลำธาร หาญตระกูล",
        "page_9_3_subname": "Lamtharn Hantrakul",
        "page_9_4_title": "Copyright",
        "page_9_4_name": "ลำธาร หาญตระกูล",
        "page_9_4_subname": "Lamtharn Hantrakul",
    },
    //Thai
    "th": {
        //1
        "page_1_title": "Creative Director<br/>Producer<br/>Music Composition<br/>Graphic Design",
        "page_1_name": "ลำธาร หาญตระกูล",
        "page_1_subname": "Lamtharn Hantrakul",
        "page_1_1_title": "Composer<br/>Creative Technologist<br/>Music AI Research Scientist",
        "page_1_1_story": "The Yaboi Hanoi project weaves music, design and technology into transcultural experiences. Lamtharn has developed intercultural audio AI tools at Google and Tiktok and has won international design awards for his cross-cultural musical instruments. He holds degrees with Distinction in Music Composition and Physics from Yale University and an M.S from Georgia Tech. He was born, raised and is currently based in Bangkok, Thailand.",
        "page_1_1_link": "www.yaboihanoi.com | Instagram @yaboihanoi | TikTok @yaboihanoi",
        //2
        "page_2_title": "Lyrics<br/>Vocals<br/>Original Track",
        "page_2_name": "ดอรช์ ดีนซ์",
        "page_2_subname": "Dorsh Deans",
        "page_2_1_title": "Singer Songwriter<br/>Music Producer",
        "page_2_1_story": "Dorsh is a Jamaican-American artist who recently released his second studio album entitled, ‘UI | UX’.  He has amassed over 6+ million streams on Spotify/Apple Music and his songs have been featured in a Netflix film and South Korean TV. Throughout his career in both music and tech, Dorsh has worked with Celebrities, World-renowned Athletes, Global Brands and Fortune 500 Companies.",
        "page_2_1_link": "https://dorshmusic.com | https://ffm.to/ui-ux",
        //3
        "page_3_title": "",
        "page_3_name": "",
        "page_3_subname": "",
        "page_3_1_title": "",
        "page_3_1_story": "",
        "page_3_1_link": "",
        //4
        "page_4_title": "",
        "page_4_name": "",
        "page_4_subname": "",
        "page_4_1_title": "",
        "page_4_1_story": "",
        "page_4_1_link": "",
        //5
        "page_5_title": "",
        "page_5_name": "",
        "page_5_subname": "",
        "page_5_1_title": "",
        "page_5_1_story": "",
        "page_5_1_link": "",
        //6
        "page_6_title": "",
        "page_6_name": "",
        "page_6_subname": "",
        "page_6_1_title": "",
        "page_6_1_story": "",
        "page_6_1_link": "",
        //7
        "page_7_title": "",
        "page_7_name": "",
        "page_7_subname": "",
        "page_7_1_title": "",
        "page_7_1_story": "",
        "page_7_1_link": "",
        //8
        "page_8_title": "",
        "page_8_name": "",
        "page_8_subname": "",
        "page_8_1_title": "",
        "page_8_1_story": "",
        "page_8_1_link": "",
        //9
        "page_9_title": "",
        "page_9_name": "",
        "page_9_subname": "",
        "page_9_1_title": "",
        "page_9_1_story": "",
        "page_9_1_link": "",
    },
    //Chinese
    "ch": {
        //1
        "page_1_title": "创造导演<br/>制片<br/>乐曲<br/>图片设计",
        "page_1_name": "ลำธาร หาญตระกูล",
        "page_1_subname": "Lamtharn Hantrakul",
        "page_1_1_title": "作曲家<br/>创作技术家<br/>音乐人工智能研究者",
        "page_1_1_story": "The Yaboi Hanoi project weaves music, design and technology into transcultural experiences. Lamtharn has developed intercultural audio AI tools at Google and Tiktok and has won international design awards for his cross-cultural musical instruments. He holds degrees with Distinction in Music Composition and Physics from Yale University and an M.S from Georgia Tech. He was born, raised and is currently based in Bangkok, Thailand.",
        "page_1_1_link": "www.yaboihanoi.com | Instagram @yaboihanoi | TikTok @yaboihanoi",
        //2
        "page_2_title": "",
        "page_2_name": "",
        "page_2_subname": "",
        "page_2_1_title": "",
        "page_2_1_story": "",
        "page_2_1_link": "",
        //3
        "page_3_title": "",
        "page_3_name": "",
        "page_3_subname": "",
        "page_3_1_title": "",
        "page_3_1_story": "",
        "page_3_1_link": "",
        //4
        "page_4_title": "",
        "page_4_name": "",
        "page_4_subname": "",
        "page_4_1_title": "",
        "page_4_1_story": "",
        "page_4_1_link": "",
        //5
        "page_5_title": "",
        "page_5_name": "",
        "page_5_subname": "",
        "page_5_1_title": "",
        "page_5_1_story": "",
        "page_5_1_link": "",
        //6
        "page_6_title": "",
        "page_6_name": "",
        "page_6_subname": "",
        "page_6_1_title": "",
        "page_6_1_story": "",
        "page_6_1_link": "",
        //7
        "page_7_title": "",
        "page_7_name": "",
        "page_7_subname": "",
        "page_7_1_title": "",
        "page_7_1_story": "",
        "page_7_1_link": "",
        //8
        "page_8_title": "",
        "page_8_name": "",
        "page_8_subname": "",
        "page_8_1_title": "",
        "page_8_1_story": "",
        "page_8_1_link": "",
        //9
        "page_9_title": "",
        "page_9_name": "",
        "page_9_subname": "",
        "page_9_1_title": "",
        "page_9_1_story": "",
        "page_9_1_link": "",
    },
}
export default locale
