const locale = {
    //Thai
    "th": {
        //1
        "page_1_title": "Creative Director<br/>Producer<br/>Music Composition<br/>Graphic Design",
        "page_1_name": "ลำธาร หาญตระกูล",
        "page_1_subname": "Lamtharn Hantrakul",
        "page_1_1_title": "Composer<br/>Creative Technologist<br/>Music AI Research Scientist",
        "page_1_1_story": "The Yaboi Hanoi project weaves music, design and technology into transcultural experiences. Lamtharn has developed intercultural audio AI tools at Google and Tiktok and has won international design awards for his cross-cultural musical instruments. He holds degrees with Distinction in Music Composition and Physics from Yale University and an M.S from Georgia Tech. He was born, raised and is currently based in Bangkok, Thailand.",
        "page_1_1_link": "www.yaboihanoi.com | Instagram @yaboihanoi | TikTok @yaboihanoi",
        //2
        "page_2_title": "",
        "page_2_name": "",
        "page_2_subname": "",
        "page_2_1_title": "",
        "page_2_1_story": "",
        "page_2_1_link": "",
        //3
        "page_3_title": "",
        "page_3_name": "",
        "page_3_subname": "",
        "page_3_1_title": "",
        "page_3_1_story": "",
        "page_3_1_link": "",
        //4
        "page_4_title": "",
        "page_4_name": "",
        "page_4_subname": "",
        "page_4_1_title": "",
        "page_4_1_story": "",
        "page_4_1_link": "",
        //5
        "page_5_title": "",
        "page_5_name": "",
        "page_5_subname": "",
        "page_5_1_title": "",
        "page_5_1_story": "",
        "page_5_1_link": "",
        //6
        "page_6_title": "",
        "page_6_name": "",
        "page_6_subname": "",
        "page_6_1_title": "",
        "page_6_1_story": "",
        "page_6_1_link": "",
        //7
        "page_7_title": "",
        "page_7_name": "",
        "page_7_subname": "",
        "page_7_1_title": "",
        "page_7_1_story": "",
        "page_7_1_link": "",
        //8
        "page_8_title": "",
        "page_8_name": "",
        "page_8_subname": "",
        "page_8_1_title": "",
        "page_8_1_story": "",
        "page_8_1_link": "",
        //9
        "page_9_title": "",
        "page_9_name": "",
        "page_9_subname": "",
        "page_9_1_title": "",
        "page_9_1_story": "",
        "page_9_1_link": "",
    },
    //English
    "en": {
        //1
        "page_1_title": "Creative Director<br/>Producer<br/>Music Composition<br/>Graphic Design",
        "page_1_name": "ลำธาร หาญตระกูล",
        "page_1_subname": "Lamtharn Hantrakul",
        "page_1_1_title": "Composer<br/>Creative Technologist<br/>Music AI Research Scientist",
        "page_1_1_story": "The Yaboi Hanoi project weaves music, design and technology into transcultural experiences. Lamtharn has developed intercultural audio AI tools at Google and Tiktok and has won international design awards for his cross-cultural musical instruments. He holds degrees with Distinction in Music Composition and Physics from Yale University and an M.S from Georgia Tech. He was born, raised and is currently based in Bangkok, Thailand.",
        "page_1_1_link": "www.yaboihanoi.com | Instagram @yaboihanoi | TikTok @yaboihanoi",
        //2
        "page_2_title": "Lyrics<br/>Vocals<br/>Original Track",
        "page_2_name": "ดอรช์ ดีนซ์",
        "page_2_subname": "Dorsh Deans",
        "page_2_1_title": "Singer Songwriter<br/>Music Producer",
        "page_2_1_story": "Dorsh is a Jamaican-American artist who recently released his second studio album entitled, ‘UI | UX’.  He has amassed over 6+ million streams on Spotify/Apple Music and his songs have been featured in a Netflix film and South Korean TV. Throughout his career in both music and tech, Dorsh has worked with Celebrities, World-renowned Athletes, Global Brands and Fortune 500 Companies.",
        "page_2_1_link": "https://dorshmusic.com | https://ffm.to/ui-ux",
        //3
        "page_3_title": "",
        "page_3_name": "",
        "page_3_subname": "",
        "page_3_1_title": "",
        "page_3_1_story": "",
        "page_3_1_link": "",
        //4
        "page_4_title": "",
        "page_4_name": "",
        "page_4_subname": "",
        "page_4_1_title": "",
        "page_4_1_story": "",
        "page_4_1_link": "",
        //5
        "page_5_title": "",
        "page_5_name": "",
        "page_5_subname": "",
        "page_5_1_title": "",
        "page_5_1_story": "",
        "page_5_1_link": "",
        //6
        "page_6_title": "",
        "page_6_name": "",
        "page_6_subname": "",
        "page_6_1_title": "",
        "page_6_1_story": "",
        "page_6_1_link": "",
        //7
        "page_7_title": "",
        "page_7_name": "",
        "page_7_subname": "",
        "page_7_1_title": "",
        "page_7_1_story": "",
        "page_7_1_link": "",
        //8
        "page_8_title": "",
        "page_8_name": "",
        "page_8_subname": "",
        "page_8_1_title": "",
        "page_8_1_story": "",
        "page_8_1_link": "",
        //9
        "page_9_title": "",
        "page_9_name": "",
        "page_9_subname": "",
        "page_9_1_title": "",
        "page_9_1_story": "",
        "page_9_1_link": "",
    },
    //Chinese
    "ch": {
        //1
        "page_1_title": "创造导演<br/>制片<br/>乐曲<br/>图片设计",
        "page_1_name": "ลำธาร หาญตระกูล",
        "page_1_subname": "Lamtharn Hantrakul",
        "page_1_1_title": "作曲家<br/>创作技术家<br/>音乐人工智能研究者",
        "page_1_1_story": "The Yaboi Hanoi project weaves music, design and technology into transcultural experiences. Lamtharn has developed intercultural audio AI tools at Google and Tiktok and has won international design awards for his cross-cultural musical instruments. He holds degrees with Distinction in Music Composition and Physics from Yale University and an M.S from Georgia Tech. He was born, raised and is currently based in Bangkok, Thailand.",
        "page_1_1_link": "www.yaboihanoi.com | Instagram @yaboihanoi | TikTok @yaboihanoi",
        //2
        "page_2_title": "",
        "page_2_name": "",
        "page_2_subname": "",
        "page_2_1_title": "",
        "page_2_1_story": "",
        "page_2_1_link": "",
        //3
        "page_3_title": "",
        "page_3_name": "",
        "page_3_subname": "",
        "page_3_1_title": "",
        "page_3_1_story": "",
        "page_3_1_link": "",
        //4
        "page_4_title": "",
        "page_4_name": "",
        "page_4_subname": "",
        "page_4_1_title": "",
        "page_4_1_story": "",
        "page_4_1_link": "",
        //5
        "page_5_title": "",
        "page_5_name": "",
        "page_5_subname": "",
        "page_5_1_title": "",
        "page_5_1_story": "",
        "page_5_1_link": "",
        //6
        "page_6_title": "",
        "page_6_name": "",
        "page_6_subname": "",
        "page_6_1_title": "",
        "page_6_1_story": "",
        "page_6_1_link": "",
        //7
        "page_7_title": "",
        "page_7_name": "",
        "page_7_subname": "",
        "page_7_1_title": "",
        "page_7_1_story": "",
        "page_7_1_link": "",
        //8
        "page_8_title": "",
        "page_8_name": "",
        "page_8_subname": "",
        "page_8_1_title": "",
        "page_8_1_story": "",
        "page_8_1_link": "",
        //9
        "page_9_title": "",
        "page_9_name": "",
        "page_9_subname": "",
        "page_9_1_title": "",
        "page_9_1_story": "",
        "page_9_1_link": "",
    },
}
export default locale